### ISSUE TITLE
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by shevek** [Enigmatis/graphql-java-annotations#232]
```
    java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
        at graphql.annotations.processor.typeFunctions.IterableFunction.buildType(IterableFunction.java:52)
        at graphql.annotations.processor.typeFunctions.DefaultTypeFunction.buildType(DefaultTypeFunction.java:104)
        at graphql.annotations.processor.retrievers.fieldBuilders.method.MethodTypeBuilder.build(MethodTypeBuilder.java:52)
        at graphql.annotations.processor.retrievers.GraphQLFieldRetriever.getField(GraphQLFieldRetriever.java:77)
        at graphql.annotations.processor.typeBuilders.OutputObjectBuilder.getOutputObjectBuilder(OutputObjectBuilder.java:81)
        at graphql.annotations.processor.retrievers.GraphQLTypeRetriever.getGraphQLType(GraphQLTypeRetriever.java:86)
        at graphql.annotations.processor.graphQLProcessors.GraphQLOutputProcessor.getOutputTypeOrRef(GraphQLOutputProcessor.java:44)
        at graphql.annotations.processor.typeFunctions.ObjectFunction.buildType(ObjectFunction.java:55)
        at graphql.annotations.processor.typeFunctions.DefaultTypeFunction.buildType(DefaultTypeFunction.java:104)
        at graphql.annotations.processor.retrievers.fieldBuilders.method.MethodTypeBuilder.build(MethodTypeBuilder.java:52)
        at graphql.annotations.processor.retrievers.GraphQLFieldRetriever.getField(GraphQLFieldRetriever.java:77)
        at graphql.annotations.processor.typeBuilders.OutputObjectBuilder.getOutputObjectBuilder(OutputObjectBuilder.java:81)
        at graphql.annotations.processor.retrievers.GraphQLTypeRetriever.getGraphQLType(GraphQLTypeRetriever.java:86)
        at graphql.annotations.processor.retrievers.GraphQLObjectHandler.getGraphQLType(GraphQLObjectHandler.java:32)
        at graphql.annotations.processor.GraphQLAnnotations.object(GraphQLAnnotations.java:124)
```

Triggered by a method returning `List<? extends String>` - in this case, IterableFunction should just use the type-bound of the wildcard. Otherwise, I have to either allocate a potentially very large collection, or break type-safety.

**Comment by Fgerthoffert** [comment]
Hi @shevek ,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,
