### ISSUE TITLE
Introduce support for subscriptions

### ISSUE THREAD

**Issue by markhamnr** [Enigmatis/graphql-java-annotations#309]
Am I wrong in thinking that subscriptions aren't supported currently?

The [README](https://github.com/Enigmatis/graphql-java-annotations/blob/master/README.md#annotations-schema-creator) implies that they are, or at least it mentions registering a Subscription class as well as a Query class and a Mutation class.

But I can't see any examples, nor can I get it to work myself.  The [GraphQL Java site](https://www.graphql-java.com/documentation/subscriptions) says that a subscription should return a Publisher, but when I try that with `AnnotationsSchemaCreator` I get an `InvalidSchemaException`: "Publisher" must define one or more fields.

Is there a way to handle subscriptions I haven't figure out yet?  Or if not, is this something that could be added?

**Comment by jkevan** [comment]
Hello @Markhamnr,  

Subscriptions are supported—we are using them in our implementation. This support is not directly related to **graphql-java-annotations** but rather to **graphql-java**. However, I agree that this specific case lacks documentation and examples.  

I'll try to help:  

### **1. WebSocket Endpoint**  
First, you need a **WebSocket endpoint** to receive subscription requests. You can find an example in our implementation:  
🔗 [[OsgiGraphQLWsEndpoint.java](https://github.com/Jahia/graphql-core/blob/master/graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/OsgiGraphQLWsEndpoint.java)](https://github.com/Jahia/graphql-core/blob/master/graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/OsgiGraphQLWsEndpoint.java)  

### **2. Base Schema Endpoint**  
You also need a base schema endpoint to register your subscriptions:  

```java
@GraphQLName("Subscription")
public static class Subscription {
}
```  

### **3. Subscription Implementation Example**  
Here’s an example of a **Subscription implementation**:  
🔗 [[GqlWorkflowSubscriptionExtension.java](https://github.com/Jahia/graphql-core/blob/master/graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/workflow/GqlWorkflowSubscriptionExtension.java)](https://github.com/Jahia/graphql-core/blob/master/graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/workflow/GqlWorkflowSubscriptionExtension.java)  

A key part that might be missing on your side is that the **Publisher should carry a GraphQL object**, like this:  

```java
Publisher<GqlWorkflowEvent>
```  

Where `GqlWorkflowEvent` is a **GraphQL object** annotated with GraphQL annotations:  

```java
@GraphQLField
@GraphQLDescription("Workflow that has just been started")
public GqlWorkflow getStartedWorkflow() {
    return startedWorkflow;
}
```  

Hope this helps! Feel free to explore the repository—it’s public and serves as the GraphQL API for our project. 🚀

**Comment by markhamnr** [comment]
OK, this is about the simplest example I can come up with:

https://gist.github.com/markhamnr/7a516ef640f353791165ef3f75478eae

When run, it gives me the `InvalidSchemaException` I mentioned above.  Is there some way I can modify it to make it a valid schema?

**Comment by jkevan** [comment]
Hello, thanks you for the gist example.

Would you have the complete stack trace error ?

**Comment by Fgerthoffert** [comment]
Hi @markhamnr 

Any updates on your end regarding this issue ?

Thanks

**Comment by markhamnr** [comment]
Argh, sorry I ignored this!

Here's the trace I get:

```Exception in thread "main" graphql.schema.validation.InvalidSchemaException: invalid schema:
"Publisher" must define one or more fields.
	at graphql.schema.GraphQLSchema$Builder.validateSchema(GraphQLSchema.java:885)
	at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:879)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:841)
	at graphql.annotations.AnnotationsSchemaCreator$Builder.build(AnnotationsSchemaCreator.java:266)
	at Main.main(Main.java:25)```

**Comment by jkevan** [comment]
Hi @markhamnr,

Thank you for your input. I agree that something doesn’t seem right here, but I’m not sure exactly what the issue is.

We do use subscriptions internally and have implemented them in some of our projects. However, our bandwidth to investigate community issues in the graphql-java-annotations project is currently limited, so we likely won’t be able to dig into this ourselves anytime soon.

If you’re still interested in this topic, we’d be happy to review a pull request if you’re able to investigate and propose a fix. We always make an effort to review and merge PRs as quickly as possible.

Thank you for your understanding!

Best regards

**Comment by Fgerthoffert** [comment]
Hi @markhamnr ,

We're closing this ticket as inactive.

Feel free to re-open the issue once you have a reproduction scenario, or even better, a PR with the corresponding fix. We'll be happy to review it then.

Thanks,

**Comment by markhamnr** [comment]
> Feel free to re-open the issue once you have a reproduction scenario, or even better, a PR with the corresponding fix.

Was there something wrong with the code snippet and stack trace I posted above?  I'm not sure what else I could provide as far as a "reproduction scenario".
